// <auto-generated />
using System;
using Cocosoft.Finance.LoanControl.Dal.Model.V2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cocosoft.Finance.LoanControl.Dal.Model.V2.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    partial class LoanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VERSION")
                        .HasColumnOrder(1);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ACCOUNT_NUMBER")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_ID")
                        .HasColumnOrder(4);

                    b.Property<int>("CustomerVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_VERSION")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_CURRENT")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_LOCKED")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id", "Version");

                    b.HasIndex("CustomerId", "CustomerVersion");

                    b.HasIndex(new[] { "AccountNumber" }, "IX_U_ACCOUNTS_ACCOUNT_NUMBER")
                        .IsUnique();

                    b.ToTable("ACCOUNTS");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VERSION")
                        .HasColumnOrder(1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ADDRESS")
                        .HasColumnOrder(9);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CITY")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("EMAIL")
                        .HasColumnOrder(7);

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IDENTIFICATION_NUMBER")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_CURRENT")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME")
                        .HasColumnOrder(4);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PHONE_NUMBER")
                        .HasColumnOrder(6);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SURNAME")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id", "Version");

                    b.HasIndex(new[] { "IdentificationNumber" }, "IX_U_CUSTOMERS_IDENTIFICATION_NUMBER")
                        .IsUnique();

                    b.ToTable("CUSTOMERS");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VERSION")
                        .HasColumnOrder(1);

                    b.Property<double>("AnnualInterest")
                        .HasColumnType("REAL")
                        .HasColumnName("ANNUAL_INTEREST")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("TEXT")
                        .HasColumnName("CURRENT_BALANCE")
                        .HasColumnOrder(8);

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_ID")
                        .HasColumnOrder(4);

                    b.Property<int>("CustomerVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_VERSION")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("DISBURSEMENT_DATE")
                        .HasColumnOrder(7);

                    b.Property<int>("DueDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DUE_DAY")
                        .HasColumnOrder(10);

                    b.Property<decimal>("Fee")
                        .HasColumnType("TEXT")
                        .HasColumnName("FEE")
                        .HasColumnOrder(9);

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("INITIAL_AMOUNT")
                        .HasColumnOrder(6);

                    b.Property<decimal>("InterestCollected")
                        .HasColumnType("TEXT")
                        .HasColumnName("INTEREST_COLLECTED")
                        .HasColumnOrder(14);

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_CLOSED")
                        .HasColumnOrder(15);

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_CURRENT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("LAST_PAYMENT_DATE")
                        .HasColumnOrder(12);

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LOAN_NUMBER")
                        .HasColumnOrder(3);

                    b.Property<int>("NumberInstalments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NUMBER_INSTALMENTS")
                        .HasColumnOrder(13);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id", "Version");

                    b.HasIndex("CustomerId", "CustomerVersion");

                    b.HasIndex(new[] { "LoanNumber" }, "IX_U_LOANS_LOAN_NUMBER")
                        .IsUnique();

                    b.ToTable("LOANS");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VERSION")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("AMOUNT")
                        .HasColumnOrder(6);

                    b.Property<decimal>("Capital")
                        .HasColumnType("TEXT")
                        .HasColumnName("CAPITAL")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATE")
                        .HasColumnOrder(5);

                    b.Property<decimal>("Interest")
                        .HasColumnType("TEXT")
                        .HasColumnName("INTEREST")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_CURRENT")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(10);

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LOAN_ID")
                        .HasColumnOrder(3);

                    b.Property<int>("LoanVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LOAN_VERSION")
                        .HasColumnOrder(4);

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("TEXT")
                        .HasColumnName("NEW_BALANCE")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id", "Version");

                    b.HasIndex("LoanId", "LoanVersion");

                    b.ToTable("PAYMENTS");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Account", b =>
                {
                    b.HasOne("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId", "CustomerVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Loan", b =>
                {
                    b.HasOne("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId", "CustomerVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Payment", b =>
                {
                    b.HasOne("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Loan", "Loan")
                        .WithMany("Payments")
                        .HasForeignKey("LoanId", "LoanVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Customer", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Cocosoft.Finance.LoanControl.Dal.Model.V2.Entities.Loan", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
